name             'php52'
maintainer       'Hisashi KOMINE'
maintainer_email 'hssh@hssh.jp'
license          'mit'
description      'Installs/Configures php52'
long_description 'Installs/Configures php52'
version          '0.1.0'
supports         'centos', '6.5'

depends 'apache2'
